[package]
name = "dynamic-analysis-kit"
version = "0.2.5"
edition = "2024"

[dependencies]

[dependencies.windows]
version = ">=0.59, <=0.62"
features = [
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_System_Memory"
]
